name: Tests

on:
  push:
  pull_request:
    types: [opened]
  schedule:
    - cron: '23 4 5 * *'

jobs:
  test:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libjson-maybexs-perl
    - name: Run tests
      run: |
        ./tests/parse_fahrplan.test.sh
